name: Testes Automatizados 

on: 
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
    #Passo 1: Checkout do código
    - name: Checkout do código 
      uses: actions/checkout@v5
    
    #Passo 2: Configurar o Node.js
    - name: Configurar o Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24'

    #Passo 3: Instalar dependências e executar testes
    - name: Instalar dependências e executar testes
      run: npm install

    #Passo 4: executar testes
    - name: Executar testes
      run: npm test
        
